version: '3.8'

services:
  app:
    container_name: orcamento-familiar-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=my-secret-pw
      - DB_NAME=orcamento_familiar
    depends_on:
      - mysql

  mysql:
    container_name: orcamento-familiar-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'orcamento_familiar'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'my-secret-pw'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
